//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HP.TS.Devops.CentralConnect.OOSRegistration
{
    using System.Runtime.Serialization;
    using System;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "IseeWebServicesHeader", Namespace = "http://www.hp.com/isee/webservices/")]
    [System.SerializableAttribute()]
    public partial class IseeWebServicesHeader : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GDIDField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string registrationTokenField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OSIDField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CSIDField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GDID
        {
            get
            {
                return this.GDIDField;
            }
            set
            {
                if ((object.ReferenceEquals(this.GDIDField, value) != true))
                {
                    this.GDIDField = value;
                    this.RaisePropertyChanged("GDID");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string registrationToken
        {
            get
            {
                return this.registrationTokenField;
            }
            set
            {
                if ((object.ReferenceEquals(this.registrationTokenField, value) != true))
                {
                    this.registrationTokenField = value;
                    this.RaisePropertyChanged("registrationToken");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public string OSID
        {
            get
            {
                return this.OSIDField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OSIDField, value) != true))
                {
                    this.OSIDField = value;
                    this.RaisePropertyChanged("OSID");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public string CSID
        {
            get
            {
                return this.CSIDField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CSIDField, value) != true))
                {
                    this.CSIDField = value;
                    this.RaisePropertyChanged("CSID");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ServiceError", Namespace = "http://www.hp.com/isee/webservices/")]
    [System.SerializableAttribute()]
    public partial class ServiceError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CodeField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsTransientErrorField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsClientErrorField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsReRegisterErrorField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                if ((this.CodeField.Equals(value) != true))
                {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTransientError
        {
            get
            {
                return this.IsTransientErrorField;
            }
            set
            {
                if ((this.IsTransientErrorField.Equals(value) != true))
                {
                    this.IsTransientErrorField = value;
                    this.RaisePropertyChanged("IsTransientError");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public bool IsClientError
        {
            get
            {
                return this.IsClientErrorField;
            }
            set
            {
                if ((this.IsClientErrorField.Equals(value) != true))
                {
                    this.IsClientErrorField = value;
                    this.RaisePropertyChanged("IsClientError");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public bool IsReRegisterError
        {
            get
            {
                return this.IsReRegisterErrorField;
            }
            set
            {
                if ((this.IsReRegisterErrorField.Equals(value) != true))
                {
                    this.IsReRegisterErrorField = value;
                    this.RaisePropertyChanged("IsReRegisterError");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.MessageField, value) != true))
                {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.hp.com/isee/webservices/", ConfigurationName = "ServiceReference1.OOSRegistrationService", SessionMode = System.ServiceModel.SessionMode.NotAllowed)]
    public interface OOSRegistrationService
    {

        // CODEGEN: Generating message contract since the wrapper name (RegistrationRequest) of message RegistrationRequest does not match the default value (Register)
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.hp.com/isee/webservices/OOSRegistrationService/Register", ReplyAction = "http://www.hp.com/isee/webservices/OOSRegistrationService/RegisterResponse")]
        OOSRegistrationServiceResult Register(RegistrationRequest request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "RegistrationRequest", WrapperNamespace = "http://www.hp.com/isee/webservices/", IsWrapped = true)]
    public partial class RegistrationRequest
    {

        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http://www.hp.com/isee/webservices/")]
        public IseeWebServicesHeader Header;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.hp.com/isee/webservices/", Order = 0)]
        public string RegistrationInformation;

        public RegistrationRequest()
        {
        }

        public RegistrationRequest(IseeWebServicesHeader Header, string RegistrationInformation)
        {
            this.Header = Header;
            this.RegistrationInformation = RegistrationInformation;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "OOSRegistrationServiceResult", WrapperNamespace = "http://www.hp.com/isee/webservices/", IsWrapped = true)]
    public partial class OOSRegistrationServiceResult
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.hp.com/isee/webservices/", Order = 0)]
        public bool IsSuccess;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.hp.com/isee/webservices/", Order = 1)]
        public ServiceError Error;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.hp.com/isee/webservices/", Order = 2)]
        public string Gdid;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.hp.com/isee/webservices/", Order = 3)]
        public int BackoffMultiplier;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.hp.com/isee/webservices/", Order = 4)]
        public System.Nullable<long> OSGdidUsn;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.hp.com/isee/webservices/", Order = 5)]
        public string HWGdid;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.hp.com/isee/webservices/", Order = 6)]
        public System.Nullable<long> HWGdidUsn;

        public OOSRegistrationServiceResult()
        {
        }

        public OOSRegistrationServiceResult(int BackoffMultiplier, ServiceError Error, string Gdid, string HWGdid, System.Nullable<long> HWGdidUsn, bool IsSuccess, System.Nullable<long> OSGdidUsn)
        {
            this.BackoffMultiplier = BackoffMultiplier;
            this.Error = Error;
            this.Gdid = Gdid;
            this.HWGdid = HWGdid;
            this.HWGdidUsn = HWGdidUsn;
            this.IsSuccess = IsSuccess;
            this.OSGdidUsn = OSGdidUsn;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OOSRegistrationServiceChannel : OOSRegistrationService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OOSRegistrationServiceClient : System.ServiceModel.ClientBase<OOSRegistrationService>, OOSRegistrationService
    {

        public OOSRegistrationServiceClient()
        {
        }

        public OOSRegistrationServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public OOSRegistrationServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public OOSRegistrationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public OOSRegistrationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OOSRegistrationServiceResult OOSRegistrationService.Register(RegistrationRequest request)
        {
            return base.Channel.Register(request);
        }

        public OOSRegistrationServiceResult Register(IseeWebServicesHeader Header, string RegistrationInformation)
        {
            RegistrationRequest inValue = new RegistrationRequest();
            inValue.Header = Header;
            inValue.RegistrationInformation = RegistrationInformation;
            return ((OOSRegistrationService)(this)).Register(inValue);
        }
    }
}