//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HP.TS.Devops.CentralConnect.Plugin.General.Resources.Metrics {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Metrics {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Metrics() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HP.TS.Devops.CentralConnect.Plugin.General.Resources.Metrics.Metrics", typeof(Metrics).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;isee:OOS-Metrics schemaVersion=&quot;5.00&quot; xmlns:cim=&quot;http://schemas.dmtf.org/wsman/2004/10/base&quot; xmlns:hpcim=&quot;http://www.hp.com/schemas/cim/2.9&quot; xmlns:isee=&quot;http://www.hp.com/schemas/isee/5.00/metrics&quot; xmlns:rsps=&quot;http://www.hp.com/schemas/rsps/5.00&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;LDID state=&quot;updated&quot;&gt;{0}&lt;/LDID&gt;
        ///  &lt;AssociatedDevice role=&quot;Hosting Device&quot;&gt;
        ///    &lt;ObjectOfServiceProperties&gt;
        ///      &lt;Property name=&quot;Transport_Enabled&quot; value=&quot;1&quot;/&gt;
        ///      &lt;Property name=&quot;Active_Status&quot; value=&quot;1&quot;/&gt;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string endpoint {
            get {
                return ResourceManager.GetString("endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;isee:ISEE-Metrics schemaVersion=&quot;5.00&quot; xmlns:cim=&quot;http://schemas.dmtf.org/wsman/2004/10/base&quot; xmlns:hpcim=&quot;http://www.hp.com/schemas/cim/2.9&quot; xmlns:isee=&quot;http://www.hp.com/schemas/isee/5.00/metrics&quot; xmlns:rsps=&quot;http://www.hp.com/schemas/rsps/5.00&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;DeploymentModel&gt;CMS&lt;/DeploymentModel&gt;
        ///  &lt;InstallationCompany&gt;TDUI Team Inc&lt;/InstallationCompany&gt;
        ///  &lt;ServiceProviderID&gt;
        ///  &lt;/ServiceProviderID&gt;
        ///  &lt;ServiceProviderName&gt;
        ///  &lt;/ServiceProviderName&gt;
        ///  &lt;DataPackageG [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
    }
}
