//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.hp.com/isee/webservices/", ConfigurationName = "DataPackageReceiverSoap")]
public interface DataPackageReceiverSoap
{

    // CODEGEN: Generating message contract since message SubmitDataPackageRequest has headers
    [System.ServiceModel.OperationContractAttribute(Action = "http://www.hp.com/isee/webservices/SubmitDataPackage", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResult))]
    SubmitDataPackageResponse SubmitDataPackage(SubmitDataPackageRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.hp.com/isee/webservices/")]
public partial class IseeWebServicesHeader
{

    private string gDIDField;

    private string registrationTokenField;

    private string oSIDField;

    private string cSIDField;

    private System.Xml.XmlAttribute[] anyAttrField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string GDID
    {
        get
        {
            return this.gDIDField;
        }
        set
        {
            this.gDIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string registrationToken
    {
        get
        {
            return this.registrationTokenField;
        }
        set
        {
            this.registrationTokenField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string OSID
    {
        get
        {
            return this.oSIDField;
        }
        set
        {
            this.oSIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public string CSID
    {
        get
        {
            return this.cSIDField;
        }
        set
        {
            this.cSIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.hp.com/isee/webservices/")]
public partial class ServiceError
{

    private int codeField;

    private bool isTransientErrorField;

    private bool isClientErrorField;

    private bool isReRegisterErrorField;

    private string messageField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public int Code
    {
        get
        {
            return this.codeField;
        }
        set
        {
            this.codeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public bool IsTransientError
    {
        get
        {
            return this.isTransientErrorField;
        }
        set
        {
            this.isTransientErrorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public bool IsClientError
    {
        get
        {
            return this.isClientErrorField;
        }
        set
        {
            this.isClientErrorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public bool IsReRegisterError
    {
        get
        {
            return this.isReRegisterErrorField;
        }
        set
        {
            this.isReRegisterErrorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public string Message
    {
        get
        {
            return this.messageField;
        }
        set
        {
            this.messageField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DataPackageSubmissionResult))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.hp.com/isee/webservices/")]
public abstract partial class ServiceResult
{

    private bool isSuccessField;

    private ServiceError errorField;

    private string gdidField;

    private int backoffMultiplierField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public bool IsSuccess
    {
        get
        {
            return this.isSuccessField;
        }
        set
        {
            this.isSuccessField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public ServiceError Error
    {
        get
        {
            return this.errorField;
        }
        set
        {
            this.errorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string Gdid
    {
        get
        {
            return this.gdidField;
        }
        set
        {
            this.gdidField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public int BackoffMultiplier
    {
        get
        {
            return this.backoffMultiplierField;
        }
        set
        {
            this.backoffMultiplierField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.hp.com/isee/webservices/")]
public partial class DataPackageSubmissionResult : ServiceResult
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "SubmitDataPackage", WrapperNamespace = "http://www.hp.com/isee/webservices/", IsWrapped = true)]
public partial class SubmitDataPackageRequest
{

    [System.ServiceModel.MessageHeaderAttribute(Namespace = "http://www.hp.com/isee/webservices/")]
    public IseeWebServicesHeader IseeWebServicesHeader;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.hp.com/isee/webservices/", Order = 0)]
    public string guid;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.hp.com/isee/webservices/", Order = 1)]
    [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
    public byte[] attachment;

    public SubmitDataPackageRequest()
    {
    }

    public SubmitDataPackageRequest(IseeWebServicesHeader IseeWebServicesHeader, string guid, byte[] attachment)
    {
        this.IseeWebServicesHeader = IseeWebServicesHeader;
        this.guid = guid;
        this.attachment = attachment;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "SubmitDataPackageResponse", WrapperNamespace = "http://www.hp.com/isee/webservices/", IsWrapped = true)]
public partial class SubmitDataPackageResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.hp.com/isee/webservices/", Order = 0)]
    public DataPackageSubmissionResult SubmitDataPackageResult;

    public SubmitDataPackageResponse()
    {
    }

    public SubmitDataPackageResponse(DataPackageSubmissionResult SubmitDataPackageResult)
    {
        this.SubmitDataPackageResult = SubmitDataPackageResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface DataPackageReceiverSoapChannel : DataPackageReceiverSoap, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class DataPackageReceiverSoapClient : System.ServiceModel.ClientBase<DataPackageReceiverSoap>, DataPackageReceiverSoap
{

    public DataPackageReceiverSoapClient()
    {
    }

    public DataPackageReceiverSoapClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public DataPackageReceiverSoapClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public DataPackageReceiverSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public DataPackageReceiverSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    SubmitDataPackageResponse DataPackageReceiverSoap.SubmitDataPackage(SubmitDataPackageRequest request)
    {
        return base.Channel.SubmitDataPackage(request);
    }

    public DataPackageSubmissionResult SubmitDataPackage(IseeWebServicesHeader IseeWebServicesHeader, string guid, byte[] attachment)
    {
        SubmitDataPackageRequest inValue = new SubmitDataPackageRequest();
        inValue.IseeWebServicesHeader = IseeWebServicesHeader;
        inValue.guid = guid;
        inValue.attachment = attachment;
        SubmitDataPackageResponse retVal = ((DataPackageReceiverSoap)(this)).SubmitDataPackage(inValue);
        return retVal.SubmitDataPackageResult;
    }
}
