//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HP.TS.Devops.CentralConnect {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HP.TS.Devops.CentralConnect.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;isee:ISEE-Registration xmlns:isee=&quot;http://www.hp.com/schemas/isee/5.00/event&quot;&gt;
        ///  &lt;RegistrationSource&gt;
        ///    &lt;HP_OOSIdentifiers&gt;
        ///      &lt;CSID&gt;
        ///        &lt;Section name=&quot;SYSTEM_IDENTIFIERS&quot;&gt;
        ///          &lt;Property name=&quot;TimestampGenerated&quot; value=&quot;{0}&quot;/&gt;
        ///          &lt;Property name=&quot;CoreSystemModel&quot; value=&quot;{1}&quot;/&gt;
        ///          &lt;Property name=&quot;UserApprovedSystemSerialNumber&quot; value=&quot;{2}&quot;/&gt;
        ///          &lt;Property name=&quot;AutoDetectedSystemSerialNumber&quot; value=&quot;{3}&quot;/&gt;
        ///          &lt;Property name=&quot;CollectorVersion&quot; value=&quot;V6.3 (B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClientRegistrationRequest {
            get {
                return ResourceManager.GetString("ClientRegistrationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;isee:ISEE-Registration xmlns:isee=&quot;http://www.hp.com/schemas/isee/5.00/event&quot;&gt;
        ///  &lt;RegistrationSource&gt;
        ///    &lt;ObjectOfServiceProperties&gt;
        ///      &lt;Property value=&quot;0&quot; name=&quot;CPServiceProviderID&quot;/&gt;
        ///      &lt;Property value=&quot;0&quot; name=&quot;CPSupportProviderID&quot;/&gt;
        ///    &lt;/ObjectOfServiceProperties&gt;
        ///    &lt;PRS_Address&gt;
        ///      &lt;Caption&gt;&lt;/Caption&gt;
        ///      &lt;Description&gt;&lt;/Description&gt;
        ///      &lt;ElementName&gt;&lt;/ElementName&gt;
        ///      &lt;DirtyFlag&gt;1&lt;/DirtyFlag&gt;
        ///      &lt;PRSUniqueName&gt;&lt;/PRSUniqueName&gt;
        ///      &lt;AddressType&gt;0&lt;/AddressType&gt;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OOSRegistrationRequest {
            get {
                return ResourceManager.GetString("OOSRegistrationRequest", resourceCulture);
            }
        }
    }
}
