//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://www.hp.com/isee/webservices/", ClrNamespace="www.hp.com.isee.webservices")]

namespace www.hp.com.isee.webservices
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IseeWebServicesHeader", Namespace="http://www.hp.com/isee/webservices/")]
    public partial class IseeWebServicesHeader : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string GDIDField;
        
        private string registrationTokenField;
        
        private string OSIDField;
        
        private string CSIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GDID
        {
            get
            {
                return this.GDIDField;
            }
            set
            {
                this.GDIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string registrationToken
        {
            get
            {
                return this.registrationTokenField;
            }
            set
            {
                this.registrationTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string OSID
        {
            get
            {
                return this.OSIDField;
            }
            set
            {
                this.OSIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string CSID
        {
            get
            {
                return this.CSIDField;
            }
            set
            {
                this.CSIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceError", Namespace="http://www.hp.com/isee/webservices/")]
    public partial class ServiceError : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> CodeField;
        
        private bool IsTransientErrorField;
        
        private bool IsClientErrorField;
        
        private bool IsReRegisterErrorField;
        
        private string MessageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTransientError
        {
            get
            {
                return this.IsTransientErrorField;
            }
            set
            {
                this.IsTransientErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool IsClientError
        {
            get
            {
                return this.IsClientErrorField;
            }
            set
            {
                this.IsClientErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool IsReRegisterError
        {
            get
            {
                return this.IsReRegisterErrorField;
            }
            set
            {
                this.IsReRegisterErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.hp.com/isee/webservices/", ConfigurationName="RemoteSupportServices", SessionMode=System.ServiceModel.SessionMode.NotAllowed)]
public interface RemoteSupportServices
{
    
    // CODEGEN: Generating message contract since the wrapper name (RemoteSupportRequest) of message RemoteSupportRequest does not match the default value (EnableVisibility)
    [System.ServiceModel.OperationContractAttribute(Action="http://www.hp.com/isee/webservices/RemoteSupportServices/EnableVisibility", ReplyAction="http://www.hp.com/isee/webservices/RemoteSupportServices/EnableVisibilityResponse" +
        "")]
    RemoteSupportResult EnableVisibility(RemoteSupportRequest request);
    
    // CODEGEN: Generating message contract since the wrapper name (RemoteSupportRequest) of message RemoteSupportRequest does not match the default value (DisableVisibility)
    [System.ServiceModel.OperationContractAttribute(Action="http://www.hp.com/isee/webservices/RemoteSupportServices/DisableVisibility", ReplyAction="http://www.hp.com/isee/webservices/RemoteSupportServices/DisableVisibilityRespons" +
        "e")]
    RemoteSupportResult DisableVisibility(RemoteSupportRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="RemoteSupportRequest", WrapperNamespace="http://www.hp.com/isee/webservices/", IsWrapped=true)]
public partial class RemoteSupportRequest
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.hp.com/isee/webservices/")]
    public www.hp.com.isee.webservices.IseeWebServicesHeader Header;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.hp.com/isee/webservices/", Order=0)]
    public string password;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.hp.com/isee/webservices/", Order=1)]
    public string username;
    
    public RemoteSupportRequest()
    {
    }
    
    public RemoteSupportRequest(www.hp.com.isee.webservices.IseeWebServicesHeader Header, string password, string username)
    {
        this.Header = Header;
        this.password = password;
        this.username = username;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="RemoteSupportResult", WrapperNamespace="http://www.hp.com/isee/webservices/", IsWrapped=true)]
public partial class RemoteSupportResult
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.hp.com/isee/webservices/", Order=0)]
    public bool IsSuccess;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.hp.com/isee/webservices/", Order=1)]
    public www.hp.com.isee.webservices.ServiceError Error;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.hp.com/isee/webservices/", Order=2)]
    public string Gdid;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.hp.com/isee/webservices/", Order=3)]
    public int BackoffMultiplier;
    
    public RemoteSupportResult()
    {
    }
    
    public RemoteSupportResult(bool IsSuccess, www.hp.com.isee.webservices.ServiceError Error, string Gdid, int BackoffMultiplier)
    {
        this.IsSuccess = IsSuccess;
        this.Error = Error;
        this.Gdid = Gdid;
        this.BackoffMultiplier = BackoffMultiplier;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface RemoteSupportServicesChannel : RemoteSupportServices, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class RemoteSupportServicesClient : System.ServiceModel.ClientBase<RemoteSupportServices>, RemoteSupportServices
{
    
    public RemoteSupportServicesClient()
    {
    }    

    public RemoteSupportServicesClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public RemoteSupportServicesClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RemoteSupportServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RemoteSupportServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    RemoteSupportResult RemoteSupportServices.EnableVisibility(RemoteSupportRequest request)
    {
        return base.Channel.EnableVisibility(request);
    }
    
    public bool EnableVisibility(www.hp.com.isee.webservices.IseeWebServicesHeader Header, string password, string username, out www.hp.com.isee.webservices.ServiceError Error, out string Gdid, out int BackoffMultiplier)
    {
        RemoteSupportRequest inValue = new RemoteSupportRequest();
        inValue.Header = Header;
        inValue.password = password;
        inValue.username = username;
        RemoteSupportResult retVal = ((RemoteSupportServices)(this)).EnableVisibility(inValue);
        Error = retVal.Error;
        Gdid = retVal.Gdid;
        BackoffMultiplier = retVal.BackoffMultiplier;
        return retVal.IsSuccess;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    RemoteSupportResult RemoteSupportServices.DisableVisibility(RemoteSupportRequest request)
    {
        return base.Channel.DisableVisibility(request);
    }
    
    public bool DisableVisibility(www.hp.com.isee.webservices.IseeWebServicesHeader Header, string password, string username, out www.hp.com.isee.webservices.ServiceError Error, out string Gdid, out int BackoffMultiplier)
    {
        RemoteSupportRequest inValue = new RemoteSupportRequest();
        inValue.Header = Header;
        inValue.password = password;
        inValue.username = username;
        RemoteSupportResult retVal = ((RemoteSupportServices)(this)).DisableVisibility(inValue);
        Error = retVal.Error;
        Gdid = retVal.Gdid;
        BackoffMultiplier = retVal.BackoffMultiplier;
        return retVal.IsSuccess;
    }
}
